[package]
name = "ni-file"
version = "0.0.1"
authors = ["monomadic"]
edition = "2018"

[dependencies]
nom = "7.1.3"
log = "0.4.17"
thiserror = "1.0.40"
glob = "0.3.1"
fastlz = "0.1.0"
time = "0.3.22"

[dev-dependencies]
wax = "0.5.0"
color-eyre = "0.6.2"
tui-tree-widget = "0.12.0"
