[package]
name = "ni-file"
version = "0.1.0"
authors = ["monomadic"]
edition = "2018"

[dependencies]
nom = "7.1.0"
log = "0.4.0"
env_logger = "0.10.0"
byteorder = "1.4.3"
rctree = "0.5.0"
binread = "2.2.0"
md5 = "0.7.0"
thiserror = "1.0.37"
anyhow = "1.0.66"

[dev-dependencies]
glob = "0.3.0"

[workspace]
members = ["cli"]
