[package]
name = "ni-decompressor"
version = "0.1.0"
authors = ["nom"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1.2"
structopt="0.3.17"
