[package]
name = "ni-file"
version = "0.1.0"
authors = ["monomadic"]
edition = "2018"

[dependencies]
nom = "7.1.3"
log = "0.4.17"
env_logger = "0.10.0"
byteorder = "1.4.3"
binread = "2.2.0"
md5 = "0.7.0"
thiserror = "1.0.38"
anyhow = "1.0.68"
loggy = "0.5.3"
glob = "0.3.1"
fastlz = "0.1.0"

[dev-dependencies]
