[package]
name = "extract-ni"
version = "0.1.0"
authors = ["nom"]
edition = "2018"

[dependencies]
nom = "7.1.0"
structopt="0.3.25"
log = "0.4.0"
env_logger = "0.9.0"
byteorder = "1.4.3"
rctree = "0.4.0"
binread = "2.2.0"
