[package]
name = "cli"
version = "0.1.0"
authors = ["monomadic"]
edition = "2021"

[[bin]]
name = "ni-file"
path = "src/main.rs"

[dependencies]
log = "0.4.0"
env_logger = "0.9.0"
structopt="0.3.25"
ni-file = { path = ".." }
